spring:
  application:
    name: eurekaserver
  security:
    basica:
      enabled: true
    user:
      name: cursoms-eureka-user
      password: ecok-usr-eeuramssur
server:
  port: 8762

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
